// Generated automatically from mod/list.oba. Do not edit.
const char* listModSource =

    "// List is an ordered sequence of values.\n"
    "// * Empty creates an empty list\n"
    "// * Cons creates a list by adding x to the list, xs.\n"
    "data List = Empty | Cons x xs\n"
    "\n"
    "// Append adds an item to the end of a list.\n"
    "fn append x xs = match xs\n"
    "| Empty     = Cons(x, Empty())\n"
    "| Cons y ys = Cons(y, append(x, ys))\n"
    ";\n"
    "\n"
    "// Length returns the length of a list.\n"
    "fn length xs  = match xs\n"
    "| Empty     = 0\n"
    "| Cons _ ys = 1 + length(ys)\n"
    ";\n"
    "\n"
    "// Where returns the items of xs for which `f(x)` returns true.\n"
    "fn where f xs = match xs\n"
    "| Empty      = xs\n"
    "| Cons y ys  = match f(y)\n"
    "| true = Cons(y, where(f,ys))\n"
    "| false = where(f, ys)\n"
    ";;\n"
    "\n"
    "// Head returns the first item in xs.\n"
    "//\n"
    "// Panics if xs is empty.\n"
    "fn head xs = match xs\n"
    "| Empty    = panic(\"list is empty\")\n"
    "| Cons x _ = x\n"
    ";\n"
    "\n"
    "// Tail returns all of the items after the first item in xs.\n"
    "//\n"
    "// If xs is empty or has length 1, the empty list is returned.\n"
    "fn tail xs = match xs\n"
    "| Empty     = xs\n"
    "| Cons _ ys = ys\n"
    ";\n"
    "\n"
    "// Concate appends the list ys to the list xs.\n"
    "fn concat xs ys = match xs\n"
    "| Empty     = ys\n"
    "| Cons x xs = Cons(x, concat(xs, ys))\n"
    ";\n"
    "\n"
    "// Format formats xs as a string 'x1,x2,...,xN'.\n"
    "fn format xs = match xs\n"
    "| Empty     = \"\"\n"
    "| Cons x xs = match xs\n"
    "| Empty     = \"%(x)\"\n"
    "| Cons y ys = \"%(x),\" + format(xs)\n"
    ";;\n"
    "\n"
    "// Quicksort sorts a list using the quicksort algorithm.\n"
    "fn quicksort xs {\n"
    "if length(xs) == 0 {\n"
    "return xs\n"
    "}\n"
    "\n"
    "let x = head(xs)\n"
    "let rest = tail(xs)\n"
    "\n"
    "fn lte v = v <= x\n"
    "fn gte v = v >= x\n"
    "\n"
    "let lesser = quicksort(where(lte, rest))\n"
    "let greater = quicksort(where(gte, rest))\n"
    "let middle = Cons(x, Empty())\n"
    "\n"
    "return concat(lesser, concat(middle, greater))\n"
    "}\n"
    "\n"
    "// Sort sorts a list.\n"
    "fn sort xs = quicksort(xs)\n"
    "\n";