// Generated automatically from mod/system.oba. Do not edit.
const char* systemModSource =

"fn print value {\n"
"__native_print(value)\n"
"return None()\n"
"}\n"
"\n"
"fn println value {\n"
"__native_println(value)\n"
"return None()\n"
"}\n"
"\n"
"fn readByte {\n"
"let byte = __native_read_byte()\n"
"if __native_is_nil(byte) {\n"
"return None()\n"
"}\n"
"return Some(byte)\n"
"}\n"
"\n"
"fn readLine {\n"
"let line = __native_read_line()\n"
"if __native_is_nil(line) {\n"
"return None()\n"
"}\n"
"return Some(line)\n"
"}\n";